
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 18 2025 22:17:46 +07 (Dec 18 2025 15:17:46 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, Y);
  input [3:0] A, B;
  input [1:0] S;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire [3:0] Y;
  wire n_0, n_1, n_2, n_6, n_7, n_8, n_9, n_12;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_25, n_26, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_53, n_54, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_66, n_67, n_69;
  wire n_84, n_91, n_116, n_118, n_120, n_136, n_140, n_150;
  wire n_152, n_153, n_154, n_156, n_166;
  NAND2XLHVT g10515__2398(.A (n_67), .B (n_69), .Y (Y[3]));
  NOR3BX1HVT g10518__5107(.AN (n_46), .B (n_60), .C (n_64), .Y (n_69));
  NAND2XLHVT g10516__6260(.A (n_63), .B (n_66), .Y (Y[2]));
  AOI21X1HVT g10525__4319(.A0 (n_34), .A1 (n_61), .B0 (n_62), .Y
       (n_67));
  NOR3X1HVT g10520__8428(.A (n_50), .B (n_49), .C (n_150), .Y (n_66));
  OAI2BB1XLHVT g10519__5526(.A0N (n_57), .A1N (n_56), .B0 (n_58), .Y
       (Y[1]));
  AOI2BB1XLHVT g10522__6783(.A0N (n_15), .A1N (n_59), .B0 (n_30), .Y
       (n_64));
  OAI21X1HVT g10517__3680(.A0 (n_44), .A1 (n_53), .B0 (n_54), .Y
       (n_63));
  NOR2X1HVT g10528__1617(.A (n_28), .B (n_61), .Y (n_62));
  NOR3XLHVT g10523__2802(.A (n_166), .B (n_47), .C (n_59), .Y (n_60));
  AOI2BB1XLHVT g10521__1705(.A0N (n_57), .A1N (n_39), .B0 (n_36), .Y
       (n_58));
  OAI2BB1X1HVT g10526__5122(.A0N (n_38), .A1N (n_51), .B0 (n_42), .Y
       (n_56));
  OAI31X4HVT g10537__7098(.A0 (n_7), .A1 (n_14), .A2 (n_152), .B0
       (n_17), .Y (n_61));
  AOI2BB1XLHVT g10524__6131(.A0N (n_31), .A1N (n_48), .B0 (n_41), .Y
       (n_53));
  NOR2X1HVT g10533__1881(.A (n_25), .B (n_32), .Y (n_59));
  MXI2XLHVT g10529__5115(.A (n_51), .B (n_20), .S0 (n_35), .Y (Y[0]));
  OAI21X1HVT g10541__7482(.A0 (n_12), .A1 (n_33), .B0 (n_18), .Y
       (n_50));
  NOR3X1HVT g10530__4733(.A (n_48), .B (n_22), .C (n_47), .Y (n_49));
  AOI32X1HVT g10532__6161(.A0 (B[3]), .A1 (A[3]), .A2 (n_16), .B0
       (n_40), .B1 (n_116), .Y (n_46));
  NOR2XLHVT g10535__9315(.A (n_43), .B (n_26), .Y (n_44));
  AOI2BB1XLHVT g10527__9945(.A0N (n_41), .A1N (n_37), .B0 (n_40), .Y
       (n_42));
  AOI22X1HVT g10531__2883(.A0 (n_38), .A1 (n_91), .B0 (n_29), .B1
       (n_37), .Y (n_39));
  NOR2XLHVT g10547__2346(.A (n_153), .B (n_35), .Y (n_36));
  NOR2XLHVT g10534__1666(.A (n_43), .B (n_166), .Y (n_34));
  INVX1HVT g10551(.A (n_33), .Y (n_54));
  NOR2X1HVT g10540__7410(.A (n_31), .B (n_156), .Y (n_32));
  NAND2XLHVT g10539__6417(.A (n_29), .B (n_84), .Y (n_30));
  NAND2X1HVT g10536__5477(.A (n_38), .B (n_84), .Y (n_28));
  OR2XLHVT g10552__2398(.A (n_19), .B (n_21), .Y (n_25));
  OR2XLHVT g10549__6260(.A (n_31), .B (n_21), .Y (n_22));
  NOR2X1HVT g10553__4319(.A (n_6), .B (n_37), .Y (n_20));
  OR2XLHVT g10550__8428(.A (n_31), .B (n_19), .Y (n_57));
  NAND2BX1HVT g10546__5526(.AN (n_17), .B (n_16), .Y (n_18));
  NOR2X1HVT g10555__6783(.A (n_15), .B (n_21), .Y (n_33));
  NAND2BX1HVT g10554__3680(.AN (n_15), .B (n_29), .Y (n_47));
  OAI21X1HVT g10545__1617(.A0 (n_51), .A1 (n_14), .B0 (n_153), .Y
       (n_26));
  NOR2X1HVT g10542__2802(.A (n_37), .B (n_19), .Y (n_48));
  INVX1HVT g10558(.A (n_16), .Y (n_35));
  INVXLHVT g10568(.A (n_40), .Y (n_12));
  INVX1HVT g10559(.A (n_29), .Y (n_41));
  NOR2X1HVT g10563__1705(.A (B[2]), .B (n_0), .Y (n_15));
  INVX1HVT g10560(.A (n_38), .Y (n_43));
  NOR2X6HVT g10576__5122(.A (A[0]), .B (n_118), .Y (n_37));
  NOR2X2HVT g10574__8246(.A (A[2]), .B (n_1), .Y (n_21));
  NOR2X1HVT g10573__7098(.A (n_8), .B (n_9), .Y (n_40));
  NOR2X2HVT g10565__6131(.A (S[0]), .B (n_9), .Y (n_16));
  NOR2X2HVT g10575__1881(.A (A[1]), .B (n_120), .Y (n_19));
  NOR2X2HVT g10566__5115(.A (S[1]), .B (n_8), .Y (n_29));
  NOR2X2HVT g10564__7482(.A (B[1]), .B (n_2), .Y (n_31));
  NOR2X1HVT g10561__4733(.A (B[2]), .B (A[2]), .Y (n_7));
  NAND2X6HVT g10577__6161(.A (B[0]), .B (A[0]), .Y (n_51));
  NOR2X1HVT g10567__9315(.A (S[0]), .B (S[1]), .Y (n_38));
  NOR2BX1HVT g10570__9945(.AN (A[0]), .B (B[0]), .Y (n_6));
  NAND2X2HVT g10571__2883(.A (B[2]), .B (A[2]), .Y (n_17));
  NOR2X2HVT g10572__2346(.A (B[1]), .B (A[1]), .Y (n_14));
  INVX1HVT g10581(.A (A[1]), .Y (n_2));
  CLKINVX4HVT g10583(.A (B[2]), .Y (n_1));
  INVX1HVT g10582(.A (A[2]), .Y (n_0));
  INVX3HVT g10580(.A (S[0]), .Y (n_8));
  CLKINVX6HVT g10584(.A (S[1]), .Y (n_9));
  MX2XLHVT g10556_0__6417(.A (A[3]), .B (n_136), .S0 (B[3]), .Y (n_84));
  INVX2HVT fopt10589(.A (n_51), .Y (n_91));
  MX2XLHVT g10586__10605(.A (A[3]), .B (n_140), .S0 (B[3]), .Y (n_116));
  CLKINVX8HVT fopt10606(.A (B[0]), .Y (n_118));
  CLKINVX4HVT fopt10607(.A (B[1]), .Y (n_120));
  INVX3HVT fopt10618(.A (A[3]), .Y (n_136));
  INVX1HVT fopt10621(.A (A[3]), .Y (n_140));
  NOR3BX1HVT g2(.AN (n_26), .B (n_43), .C (n_54), .Y (n_150));
  NOR2BX2HVT g10629(.AN (n_154), .B (n_91), .Y (n_152));
  NAND2X1HVT g10562__10630(.A (B[1]), .B (A[1]), .Y (n_153));
  NAND2X2HVT g10562__1666_0(.A (B[1]), .B (A[1]), .Y (n_154));
  INVX2HVT fopt1(.A (n_37), .Y (n_156));
  XOR2XLHVT g10637(.A (A[3]), .B (B[3]), .Y (n_166));
endmodule

