
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 15 2025 22:51:57 +07 (Dec 15 2025 15:51:57 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, Y);
  input [3:0] A, B;
  input [1:0] S;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire [3:0] Y;
  wire n_1, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_17, n_18;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_38;
  OAI222X1HVT g653__2398(.A0 (n_25), .A1 (n_9), .B0 (S[1]), .B1 (n_23),
       .C0 (n_8), .C1 (n_24), .Y (Y[3]));
  OAI222XLHVT g654__5107(.A0 (n_25), .A1 (n_4), .B0 (S[1]), .B1 (n_22),
       .C0 (n_3), .C1 (n_24), .Y (Y[2]));
  XNOR2X1HVT g655__6260(.A (n_15), .B (n_20), .Y (n_23));
  INVX1HVT g656(.A (n_21), .Y (n_22));
  ADDFX1HVT g657__4319(.A (A[2]), .B (n_13), .CI (n_16), .CO (n_20), .S
       (n_21));
  OAI222XLHVT g658__8428(.A0 (n_25), .A1 (n_7), .B0 (S[1]), .B1 (n_18),
       .C0 (n_6), .C1 (n_24), .Y (Y[1]));
  INVX1HVT g659(.A (n_17), .Y (n_18));
  ADDFX1HVT g660__5526(.A (A[1]), .B (n_12), .CI (n_5), .CO (n_16), .S
       (n_17));
  XNOR2X1HVT g663__6783(.A (A[3]), .B (n_10), .Y (n_15));
  MX2XLHVT g669__1617(.A (S[0]), .B (n_11), .S0 (B[2]), .Y (n_13));
  OAI21X1HVT g662__2802(.A0 (B[0]), .A1 (n_11), .B0 (n_1), .Y (n_12));
  MXI2XLHVT g670__1705(.A (S[0]), .B (n_11), .S0 (B[3]), .Y (n_10));
  OAI21X1HVT g666__5122(.A0 (B[3]), .A1 (A[3]), .B0 (n_8), .Y (n_9));
  OAI21X1HVT g665__8246(.A0 (B[1]), .A1 (A[1]), .B0 (n_6), .Y (n_7));
  MXI2XLHVT g671__7098(.A (n_11), .B (S[0]), .S0 (B[1]), .Y (n_5));
  OAI21X1HVT g667__6131(.A0 (B[2]), .A1 (A[2]), .B0 (n_3), .Y (n_4));
  NAND2X1HVT g674__1881(.A (S[1]), .B (n_11), .Y (n_24));
  NAND2X1HVT g672__7482(.A (B[3]), .B (A[3]), .Y (n_8));
  NAND2X1HVT g677__4733(.A (B[2]), .B (A[2]), .Y (n_3));
  NAND2X1HVT g675__6161(.A (B[1]), .B (A[1]), .Y (n_6));
  NAND2X1HVT g676__9315(.A (B[0]), .B (A[0]), .Y (n_1));
  NAND2X1HVT g673__9945(.A (S[0]), .B (S[1]), .Y (n_25));
  INVX1HVT g678(.A (S[0]), .Y (n_11));
  MXI2XLHVT g2(.A (n_1), .B (n_38), .S0 (n_24), .Y (Y[0]));
  XNOR2X1HVT g3(.A (B[0]), .B (A[0]), .Y (n_38));
endmodule

