
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 00:59:37 +07 (Nov 19 2025 17:59:37 UTC)

// Verification Directory fv/NAND2 

module NAND2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  NAND2XLLVT g4__2398(.A (B), .B (A), .Y (Y));
endmodule

