
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 14 2025 22:47:57 +07 (Dec 14 2025 15:47:57 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, clk, Y);
  input [3:0] A, B;
  input [1:0] S;
  input clk;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire clk;
  wire [3:0] Y;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_55;
  DFFQXLHVT \Y_reg[3] (.CK (clk), .D (n_43), .Q (Y[3]));
  OAI211X1HVT g764__2398(.A0 (n_37), .A1 (n_41), .B0 (n_32), .C0
       (n_39), .Y (n_43));
  DFFQXLHVT \Y_reg[2] (.CK (clk), .D (n_42), .Q (Y[2]));
  DFFQXLHVT \Y_reg[1] (.CK (clk), .D (n_40), .Q (Y[1]));
  OAI211X1HVT g766__5107(.A0 (n_33), .A1 (n_27), .B0 (n_26), .C0
       (n_35), .Y (n_42));
  AOI221X1HVT g767__6260(.A0 (n_30), .A1 (n_31), .B0 (n_38), .B1
       (n_29), .C0 (n_34), .Y (n_41));
  INVX1HVT g773(.A (n_36), .Y (n_40));
  AOI33XLHVT g768__4319(.A0 (n_38), .A1 (n_37), .A2 (n_28), .B0 (B[3]),
       .B1 (A[3]), .B2 (n_25), .Y (n_39));
  AOI221X1HVT g774__8428(.A0 (n_21), .A1 (n_15), .B0 (n_38), .B1
       (n_55), .C0 (n_22), .Y (n_36));
  OAI21X1HVT g777__5526(.A0 (n_34), .A1 (n_18), .B0 (n_33), .Y (n_35));
  NAND3BXLHVT g778__6783(.AN (n_31), .B (n_30), .C (n_37), .Y (n_32));
  INVXLHVT g770(.A (n_28), .Y (n_29));
  AOI22X1HVT g771__3680(.A0 (n_38), .A1 (n_16), .B0 (n_30), .B1 (n_24),
       .Y (n_27));
  AOI32X1HVT g775__1617(.A0 (n_38), .A1 (n_33), .A2 (n_20), .B0 (n_25),
       .B1 (n_23), .Y (n_26));
  SDFFQX1HVT \Y_reg[0] (.CK (clk), .D (n_9), .SI (n_14), .SE (n_25), .Q
       (Y[0]));
  AOI21X1HVT g779__2802(.A0 (n_1), .A1 (n_24), .B0 (n_23), .Y (n_31));
  OAI32X1HVT g784__1705(.A0 (n_13), .A1 (n_17), .A2 (n_21), .B0 (n_12),
       .B1 (n_4), .Y (n_22));
  AOI21X1HVT g772__5122(.A0 (n_10), .A1 (n_20), .B0 (n_11), .Y (n_28));
  NOR2X1HVT g783__7098(.A (n_17), .B (n_24), .Y (n_18));
  INVX1HVT g780(.A (n_20), .Y (n_16));
  OAI21X1HVT g787__6131(.A0 (n_14), .A1 (n_17), .B0 (n_5), .Y (n_15));
  OAI21X1HVT g782__1881(.A0 (n_8), .A1 (n_7), .B0 (n_6), .Y (n_20));
  OAI21X1HVT g786__5115(.A0 (n_0), .A1 (n_13), .B0 (n_12), .Y (n_24));
  NAND2BX1HVT g788__7482(.AN (n_11), .B (n_10), .Y (n_33));
  NAND2BXLHVT g790__4733(.AN (n_8), .B (n_2), .Y (n_9));
  NAND2BX1HVT g789__6161(.AN (n_7), .B (n_6), .Y (n_21));
  INVX1HVT g792(.A (n_13), .Y (n_14));
  INVX1HVT g800(.A (n_5), .Y (n_34));
  XNOR2X1HVT g791__9315(.A (B[3]), .B (A[3]), .Y (n_37));
  INVX1HVT g801(.A (n_25), .Y (n_4));
  INVX1HVT g802(.A (n_30), .Y (n_17));
  NAND2BX1HVT g793__9945(.AN (B[0]), .B (A[0]), .Y (n_2));
  NAND2X1HVT g794__2883(.A (B[1]), .B (A[1]), .Y (n_12));
  AND2XLHVT g795__2346(.A (B[2]), .B (A[2]), .Y (n_23));
  NAND2X1HVT g807__1666(.A (S[0]), .B (S[1]), .Y (n_5));
  NOR2BX1HVT g796__7410(.AN (B[1]), .B (A[1]), .Y (n_7));
  NAND2BX1HVT g797__6417(.AN (B[1]), .B (A[1]), .Y (n_6));
  NOR2X1HVT g810__5477(.A (S[0]), .B (S[1]), .Y (n_30));
  OR2XLHVT g803__2398(.A (B[2]), .B (A[2]), .Y (n_1));
  NOR2X1HVT g804__5107(.A (B[1]), .B (A[1]), .Y (n_0));
  NOR2BX1HVT g806__6260(.AN (A[2]), .B (B[2]), .Y (n_11));
  NAND2BX1HVT g805__4319(.AN (A[2]), .B (B[2]), .Y (n_10));
  NOR2BX1HVT g808__8428(.AN (B[0]), .B (A[0]), .Y (n_8));
  NAND2X1HVT g798__5526(.A (B[0]), .B (A[0]), .Y (n_13));
  NOR2BX1HVT g809__6783(.AN (S[1]), .B (S[0]), .Y (n_25));
  NOR2BX1HVT g799__3680(.AN (S[0]), .B (S[1]), .Y (n_38));
  XOR2XLHVT g2(.A (n_8), .B (n_21), .Y (n_55));
endmodule

