
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 18 2025 10:52:05 +07 (Dec 18 2025 03:52:05 UTC)

// Verification Directory fv/alu_low_power 

module alu_low_power(A, B, S, clk, Y);
  input [3:0] A, B;
  input [1:0] S;
  input clk;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire clk;
  wire [3:0] Y;
  wire [3:0] sub_res;
  wire [3:0] add_res;
  wire [3:0] xor_res;
  wire [3:0] and_res;
  wire en_add, en_and, en_sub, en_xor, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  CLKAND2X6HVT g588__2398(.A (S[0]), .B (S[1]), .Y (en_xor));
  NOR2X1HVT g589__5107(.A (S[0]), .B (S[1]), .Y (en_add));
  NOR2X2HVT g590__6260(.A (S[1]), .B (n_43), .Y (en_sub));
  INVX2HVT g593(.A (S[0]), .Y (n_43));
  NOR2BX2HVT g2__4319(.AN (S[1]), .B (S[0]), .Y (en_and));
  NAND2XLHVT g1104__8428(.A (n_42), .B (n_33), .Y (Y[3]));
  AOI22X1HVT g1105__5526(.A0 (sub_res[3]), .A1 (en_sub), .B0
       (add_res[3]), .B1 (en_add), .Y (n_42));
  NAND2XLHVT g1106__6783(.A (n_41), .B (n_26), .Y (Y[2]));
  DFFQXLHVT \sub_res_reg[3] (.CK (n_39), .D (n_40), .Q (sub_res[3]));
  AOI22X1HVT g1108__3680(.A0 (sub_res[2]), .A1 (en_sub), .B0
       (add_res[2]), .B1 (en_add), .Y (n_41));
  NAND2XLHVT g1109__1617(.A (n_38), .B (n_27), .Y (Y[1]));
  XNOR2X1HVT g1110__2802(.A (n_15), .B (n_37), .Y (n_40));
  DFFQXLHVT \add_res_reg[3] (.CK (n_34), .D (n_36), .Q (add_res[3]));
  DFFQXLHVT \sub_res_reg[2] (.CK (n_39), .D (n_35), .Q (sub_res[2]));
  AOI22X1HVT g1113__1705(.A0 (sub_res[1]), .A1 (en_sub), .B0
       (add_res[1]), .B1 (en_add), .Y (n_38));
  NAND2XLHVT g1114__5122(.A (n_31), .B (n_32), .Y (Y[0]));
  AOI21X1HVT g1115__8246(.A0 (n_3), .A1 (n_30), .B0 (n_4), .Y (n_37));
  XNOR2X1HVT g1116__7098(.A (n_15), .B (n_29), .Y (n_36));
  XNOR2X1HVT g1117__6131(.A (n_14), .B (n_30), .Y (n_35));
  DFFQXLHVT \sub_res_reg[1] (.CK (n_39), .D (n_25), .Q (sub_res[1]));
  DFFQXLHVT \add_res_reg[2] (.CK (n_34), .D (n_28), .Q (add_res[2]));
  AOI22X1HVT g1120__1881(.A0 (xor_res[3]), .A1 (en_xor), .B0
       (and_res[3]), .B1 (en_and), .Y (n_33));
  AOI22X1HVT g1121__5115(.A0 (xor_res[0]), .A1 (en_xor), .B0
       (and_res[0]), .B1 (en_and), .Y (n_32));
  AOI22X1HVT g1122__7482(.A0 (sub_res[0]), .A1 (en_sub), .B0
       (add_res[0]), .B1 (en_add), .Y (n_31));
  DFFQXLHVT \add_res_reg[1] (.CK (n_34), .D (n_22), .Q (add_res[1]));
  NAND2X1HVT g1124__4733(.A (n_1), .B (n_24), .Y (n_29));
  OAI21X1HVT g1125__6161(.A0 (n_10), .A1 (n_7), .B0 (n_13), .Y (n_30));
  XOR2XLHVT g1126__9315(.A (n_20), .B (n_14), .Y (n_28));
  AOI22X1HVT g1127__9945(.A0 (xor_res[1]), .A1 (en_xor), .B0
       (and_res[1]), .B1 (en_and), .Y (n_27));
  AOI22X1HVT g1128__2883(.A0 (xor_res[2]), .A1 (en_xor), .B0
       (and_res[2]), .B1 (en_and), .Y (n_26));
  XNOR2X1HVT g1129__2346(.A (n_7), .B (n_16), .Y (n_25));
  DFFQXLHVT \sub_res_reg[0] (.CK (n_39), .D (n_18), .Q (sub_res[0]));
  DFFQXLHVT \xor_res_reg[3] (.CK (n_23), .D (n_21), .Q (xor_res[3]));
  DFFQXLHVT \and_res_reg[3] (.CK (n_19), .D (n_0), .Q (and_res[3]));
  OAI21X1HVT g1133__1666(.A0 (B[2]), .A1 (A[2]), .B0 (n_20), .Y (n_24));
  DFFQXLHVT \add_res_reg[0] (.CK (n_34), .D (n_18), .Q (add_res[0]));
  DFFQXLHVT \xor_res_reg[0] (.CK (n_23), .D (n_18), .Q (xor_res[0]));
  XOR2XLHVT g1136__7410(.A (n_8), .B (n_16), .Y (n_22));
  INVXLHVT g1137(.A (n_15), .Y (n_21));
  DFFQXLHVT \xor_res_reg[1] (.CK (n_23), .D (n_17), .Q (xor_res[1]));
  DFFQXLHVT \xor_res_reg[2] (.CK (n_23), .D (n_14), .Q (xor_res[2]));
  OAI21X1HVT g1140__6417(.A0 (n_5), .A1 (n_8), .B0 (n_11), .Y (n_20));
  DFFQXLHVT \and_res_reg[2] (.CK (n_19), .D (n_2), .Q (and_res[2]));
  DFFQXLHVT \and_res_reg[0] (.CK (n_19), .D (n_9), .Q (and_res[0]));
  DFFQXLHVT \and_res_reg[1] (.CK (n_19), .D (n_12), .Q (and_res[1]));
  INVXLHVT g1144(.A (n_16), .Y (n_17));
  NAND2BXLHVT g1145__5477(.AN (n_7), .B (n_6), .Y (n_18));
  NOR2BX1HVT g1146__2398(.AN (n_13), .B (n_10), .Y (n_16));
  XNOR2X1HVT g1147__5107(.A (B[3]), .B (A[3]), .Y (n_15));
  NAND2BX1HVT g1148__6260(.AN (n_4), .B (n_3), .Y (n_14));
  INVXLHVT g1149(.A (n_11), .Y (n_12));
  INVXLHVT g1150(.A (n_8), .Y (n_9));
  NAND2BX1HVT g1151__4319(.AN (B[0]), .B (A[0]), .Y (n_6));
  NOR2X1HVT g1152__8428(.A (B[1]), .B (A[1]), .Y (n_5));
  NAND2BX1HVT g1153__5526(.AN (B[1]), .B (A[1]), .Y (n_13));
  NAND2X1HVT g1154__6783(.A (B[1]), .B (A[1]), .Y (n_11));
  NOR2BX1HVT g1155__3680(.AN (B[1]), .B (A[1]), .Y (n_10));
  NAND2X1HVT g1156__1617(.A (B[0]), .B (A[0]), .Y (n_8));
  NOR2BX1HVT g1157__2802(.AN (B[0]), .B (A[0]), .Y (n_7));
  INVXLHVT g1158(.A (n_1), .Y (n_2));
  AND2XLHVT g1159__1705(.A (B[3]), .B (A[3]), .Y (n_0));
  NOR2BX1HVT g1160__5122(.AN (A[2]), .B (B[2]), .Y (n_4));
  NAND2BX1HVT g1161__8246(.AN (A[2]), .B (B[2]), .Y (n_3));
  NAND2X1HVT g1162__7098(.A (B[2]), .B (A[2]), .Y (n_1));
  AND2XLHVT g1163__6131(.A (clk), .B (en_add), .Y (n_34));
  AND2XLHVT g1164__1881(.A (clk), .B (en_sub), .Y (n_39));
  AND2XLHVT g1165__5115(.A (clk), .B (en_and), .Y (n_19));
  AND2XLHVT g1166__7482(.A (clk), .B (en_xor), .Y (n_23));
endmodule

