
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 00:18:25 +07 (Nov 19 2025 17:18:25 UTC)

// Verification Directory fv/dff 

module dff(clk, d, q);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFQXLHVT q_reg(.CK (clk), .D (d), .Q (q));
endmodule

