
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 02:39:17 +07 (Nov 19 2025 19:39:17 UTC)

// Verification Directory fv/full_adder 

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  ADDFX1LVT g79__2398(.A (B), .B (A), .CI (Cin), .CO (Cout), .S (S));
endmodule

