
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 16 2025 20:57:23 +07 (Dec 16 2025 13:57:23 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, Y);
  input [3:0] A, B;
  input [1:0] S;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire [3:0] Y;
  wire n_0, n_2, n_3, n_4, n_6, n_7, n_9, n_10;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_27, n_29, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_43, n_44, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_61, n_62;
  wire n_63, n_65, n_79, n_87, n_89, n_90, n_92, n_97;
  wire n_98, n_101, n_102, n_103, n_104, n_105, n_108;
  NAND4XLHVT g8673__2398(.A (n_37), .B (n_62), .C (n_105), .D (n_63),
       .Y (Y[3]));
  NAND2XLHVT g8672__5107(.A (n_65), .B (n_52), .Y (Y[2]));
  NOR2XLHVT g8674__6260(.A (n_49), .B (n_59), .Y (n_65));
  NOR2XLHVT g8679__8428(.A (n_101), .B (n_55), .Y (n_63));
  NAND4XLHVT g8684__5526(.A (n_61), .B (n_57), .C (n_79), .D (n_56), .Y
       (n_62));
  OAI21XLHVT g8675__6783(.A0 (n_50), .A1 (n_36), .B0 (n_51), .Y (Y[1]));
  OAI21XLHVT g8687__3680(.A0 (n_54), .A1 (n_103), .B0 (n_39), .Y
       (n_59));
  NAND2XLHVT g8681__1617(.A (n_57), .B (n_56), .Y (n_58));
  OAI21XLHVT g8682__2802(.A0 (n_54), .A1 (n_32), .B0 (n_97), .Y (n_55));
  AOI31XLHVT g8676__5122(.A0 (n_61), .A1 (n_48), .A2 (n_47), .B0
       (n_40), .Y (n_52));
  AOI21XLHVT g8678__8246(.A0 (n_27), .A1 (n_50), .B0 (n_20), .Y (n_51));
  NOR3XLHVT g8677__7098(.A (n_25), .B (n_48), .C (n_47), .Y (n_49));
  MXI2XLHVT g8686__6131(.A (n_35), .B (n_104), .S0 (n_19), .Y (Y[0]));
  AOI21XLHVT g8688__5115(.A0 (n_21), .A1 (n_43), .B0 (n_24), .Y (n_44));
  OAI21XLHVT g8696__4733(.A0 (n_9), .A1 (n_48), .B0 (n_14), .Y (n_40));
  NAND3XLHVT g8697__6161(.A (n_38), .B (n_15), .C (n_54), .Y (n_39));
  OAI21XLHVT g8693__9315(.A0 (n_29), .A1 (n_34), .B0 (n_108), .Y
       (n_56));
  AOI32XLHVT g8691__9945(.A0 (B[3]), .A1 (A[3]), .A2 (n_13), .B0
       (n_33), .B1 (n_43), .Y (n_37));
  AOI221XLHVT g8685__2883(.A0 (n_38), .A1 (n_35), .B0 (n_61), .B1
       (n_34), .C0 (n_33), .Y (n_36));
  NAND3XLHVT g8695__2346(.A (n_38), .B (n_23), .C (n_43), .Y (n_32));
  AOI21X1HVT g8689__7410(.A0 (n_34), .A1 (n_98), .B0 (n_29), .Y (n_47));
  OAI22XLHVT g8690__5477(.A0 (n_102), .A1 (n_35), .B0 (n_34), .B1
       (n_25), .Y (n_27));
  NOR2XLHVT g8694__2398(.A (n_23), .B (n_43), .Y (n_24));
  NOR2XLHVT g8701__5107(.A (n_21), .B (n_102), .Y (n_22));
  NOR2XLHVT g8702__6260(.A (n_16), .B (n_19), .Y (n_20));
  NOR2BX1HVT g8708__4319(.AN (n_98), .B (n_29), .Y (n_50));
  NOR2X1HVT g8709__8428(.A (n_17), .B (n_10), .Y (n_48));
  OAI21X2HVT g8699__5526(.A0 (n_35), .A1 (n_7), .B0 (n_16), .Y (n_54));
  NAND2BXLHVT g8703__6783(.AN (n_21), .B (n_23), .Y (n_15));
  NAND2BXLHVT g8704__3680(.AN (n_23), .B (n_13), .Y (n_14));
  INVX1HVT g8723(.A (n_25), .Y (n_61));
  INVXLHVT g8722(.A (n_10), .Y (n_57));
  OAI22X4HVT g8710__1617(.A0 (B[3]), .A1 (n_92), .B0 (A[3]), .B1 (n_0),
       .Y (n_43));
  INVXLHVT g8713(.A (n_13), .Y (n_19));
  INVX1HVT g8711(.A (n_9), .Y (n_33));
  NOR2X1HVT g8728__2802(.A (B[1]), .B (n_90), .Y (n_29));
  NAND2X2HVT g8719__1705(.A (B[0]), .B (n_87), .Y (n_34));
  NOR2X1HVT g8729__5122(.A (B[2]), .B (n_3), .Y (n_10));
  NOR2X1HVT g8725__8246(.A (A[2]), .B (n_2), .Y (n_17));
  NAND2X1HVT g8731__7098(.A (S[0]), .B (n_4), .Y (n_25));
  NAND2X2HVT g8726__6131(.A (B[1]), .B (n_89), .Y (n_18));
  NOR2X2HVT g8715__1881(.A (B[1]), .B (A[1]), .Y (n_7));
  NAND2X1HVT g8717__5115(.A (S[0]), .B (S[1]), .Y (n_9));
  NOR2X1HVT g8727__7482(.A (B[2]), .B (A[2]), .Y (n_21));
  NOR2X4HVT g8732__4733(.A (S[0]), .B (S[1]), .Y (n_38));
  NOR2BX1HVT g8714__6161(.AN (A[0]), .B (B[0]), .Y (n_6));
  NAND2X1HVT g8716__9315(.A (B[1]), .B (A[1]), .Y (n_16));
  NOR2BX1HVT g8720__9945(.AN (S[1]), .B (S[0]), .Y (n_13));
  NAND2X1HVT g8718__2883(.A (B[2]), .B (A[2]), .Y (n_23));
  NAND2X4HVT g8730__2346(.A (B[0]), .B (A[0]), .Y (n_35));
  INVX1HVT g8739(.A (S[1]), .Y (n_4));
  INVX1HVT g8735(.A (A[2]), .Y (n_3));
  INVX2HVT g8738(.A (B[2]), .Y (n_2));
  INVX2HVT g8733(.A (B[3]), .Y (n_0));
  INVXLHVT fopt1(.A (n_43), .Y (n_79));
  INVX3HVT fopt8743(.A (A[0]), .Y (n_87));
  CLKINVX4HVT fopt8744(.A (A[1]), .Y (n_89));
  INVXLHVT fopt8745(.A (A[1]), .Y (n_90));
  CLKINVX8HVT fopt8746(.A (A[3]), .Y (n_92));
  NAND3BXLHVT g2(.AN (n_43), .B (n_22), .C (n_54), .Y (n_97));
  BUFX2HVT fopt8749(.A (n_18), .Y (n_98));
  NOR2BXLHVT g8751(.AN (n_38), .B (n_44), .Y (n_101));
  INVXLHVT g8752(.A (n_38), .Y (n_102));
  NAND2BXLHVT g8753(.AN (n_48), .B (n_38), .Y (n_103));
  NOR2BX1HVT g8754(.AN (n_34), .B (n_6), .Y (n_104));
  NAND3BXLHVT g8755(.AN (n_79), .B (n_61), .C (n_58), .Y (n_105));
  NOR2BXLHVT g8756(.AN (n_18), .B (n_17), .Y (n_108));
endmodule

