
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 18 2025 22:06:51 +07 (Nov 18 2025 15:06:51 UTC)

// Verification Directory fv/dff 

module dff(clk, d, q);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1LVT q_reg(.CK (clk), .D (d), .Q (q));
endmodule

