
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 23:08:22 +07 (Nov 19 2025 16:08:22 UTC)

// Verification Directory fv/NOT 

module NOT(A, Y);
  input A;
  output Y;
  wire A;
  wire Y;
  INVXLLVT g2(.A (A), .Y (Y));
endmodule

