
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 15 2025 22:59:48 +07 (Dec 15 2025 15:59:48 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, Y);
  input [3:0] A, B;
  input [1:0] S;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire [3:0] Y;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_41, n_43, n_44;
  wire n_56;
  OAI211X1HVT g776__2398(.A0 (n_43), .A1 (n_41), .B0 (n_14), .C0
       (n_44), .Y (Y[3]));
  NAND2X1HVT g777__5107(.A (n_43), .B (n_39), .Y (n_44));
  OAI211X1HVT g778__6260(.A0 (n_34), .A1 (n_31), .B0 (n_33), .C0
       (n_35), .Y (Y[2]));
  AOI22X1HVT g779__4319(.A0 (n_32), .A1 (n_36), .B0 (n_30), .B1 (n_38),
       .Y (n_41));
  OAI211X1HVT g783__8428(.A0 (n_37), .A1 (n_15), .B0 (n_23), .C0
       (n_29), .Y (Y[1]));
  OAI22X1HVT g780__5526(.A0 (n_26), .A1 (n_38), .B0 (n_37), .B1 (n_36),
       .Y (n_39));
  NAND2X1HVT g785__6783(.A (n_34), .B (n_27), .Y (n_35));
  AOI32X1HVT g784__3680(.A0 (n_32), .A1 (n_34), .A2 (n_24), .B0 (n_19),
       .B1 (n_28), .Y (n_33));
  AOI22X1HVT g781__1617(.A0 (n_32), .A1 (n_13), .B0 (n_30), .B1 (n_25),
       .Y (n_31));
  NOR2X1HVT g795__2802(.A (n_56), .B (n_18), .Y (n_29));
  NAND2BX1HVT g788__1705(.AN (n_28), .B (n_21), .Y (n_38));
  OAI21X1HVT g787__5122(.A0 (n_26), .A1 (n_25), .B0 (n_22), .Y (n_27));
  AOI21X1HVT g782__8246(.A0 (n_7), .A1 (n_24), .B0 (n_8), .Y (n_36));
  OAI2BB1X1HVT g793__7098(.A0N (n_22), .A1N (n_9), .B0 (n_16), .Y
       (n_23));
  OAI21X1HVT g794__6131(.A0 (B[2]), .A1 (A[2]), .B0 (n_25), .Y (n_21));
  MXI2XLHVT g790__1881(.A (n_6), .B (n_17), .S0 (n_19), .Y (Y[0]));
  NOR3XLHVT g797__5115(.A (n_17), .B (n_26), .C (n_16), .Y (n_18));
  XNOR2X1HVT g791__7482(.A (n_10), .B (n_16), .Y (n_15));
  AOI32X1HVT g792__4733(.A0 (B[3]), .A1 (A[3]), .A2 (n_19), .B0 (n_3),
       .B1 (n_43), .Y (n_14));
  INVX1HVT g786(.A (n_24), .Y (n_13));
  OAI21X1HVT g796__6161(.A0 (n_0), .A1 (n_17), .B0 (n_11), .Y (n_25));
  OAI21X1HVT g789__9945(.A0 (n_5), .A1 (n_10), .B0 (n_4), .Y (n_24));
  NAND2XLHVT g798__2883(.A (n_30), .B (n_17), .Y (n_9));
  NAND2BX1HVT g800__2346(.AN (n_8), .B (n_7), .Y (n_34));
  NOR2X1HVT g801__1666(.A (n_1), .B (n_10), .Y (n_6));
  NAND2BX1HVT g803__7410(.AN (n_5), .B (n_4), .Y (n_16));
  INVX1HVT g804(.A (n_22), .Y (n_3));
  INVX1HVT g813(.A (n_32), .Y (n_37));
  CLKXOR2X1HVT g802__6417(.A (B[3]), .B (A[3]), .Y (n_43));
  INVX1HVT g814(.A (n_30), .Y (n_26));
  NOR2BX1HVT g806__5477(.AN (A[0]), .B (B[0]), .Y (n_1));
  NOR2BX1HVT g807__2398(.AN (B[1]), .B (A[1]), .Y (n_5));
  NAND2BX1HVT g808__5107(.AN (B[1]), .B (A[1]), .Y (n_4));
  NAND2X1HVT g816__6260(.A (B[1]), .B (A[1]), .Y (n_11));
  AND2XLHVT g815__4319(.A (B[2]), .B (A[2]), .Y (n_28));
  NOR2BX1HVT g817__8428(.AN (B[0]), .B (A[0]), .Y (n_10));
  NAND2X1HVT g811__5526(.A (S[0]), .B (S[1]), .Y (n_22));
  NOR2X1HVT g805__6783(.A (B[1]), .B (A[1]), .Y (n_0));
  NOR2BX1HVT g810__3680(.AN (A[2]), .B (B[2]), .Y (n_8));
  NAND2BX1HVT g809__1617(.AN (A[2]), .B (B[2]), .Y (n_7));
  NOR2BX1HVT g820__2802(.AN (S[0]), .B (S[1]), .Y (n_32));
  NOR2X1HVT g821__1705(.A (S[0]), .B (S[1]), .Y (n_30));
  NAND2X1HVT g818__5122(.A (B[0]), .B (A[0]), .Y (n_17));
  NOR2BX1HVT g819__8246(.AN (S[1]), .B (S[0]), .Y (n_19));
  NOR2BX1HVT g2(.AN (n_19), .B (n_11), .Y (n_56));
endmodule

