
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 18 2025 22:31:50 +07 (Dec 18 2025 15:31:50 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, Y);
  input [3:0] A, B;
  input [1:0] S;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire [3:0] Y;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_35, n_37, n_38, n_40, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_71, n_84, n_92, n_93, n_95;
  wire n_101, n_103, n_105, n_110, n_111, n_113, n_114, n_121;
  wire n_122;
  NAND3XLHVT g12528__2398(.A (n_68), .B (n_69), .C (n_65), .Y (Y[3]));
  NAND2XLHVT g12529__5107(.A (n_67), .B (n_71), .Y (Y[2]));
  OAI21X1HVT g12531__6260(.A0 (n_121), .A1 (n_64), .B0 (n_45), .Y
       (n_71));
  OAI21XLHVT g12532__4319(.A0 (n_29), .A1 (n_42), .B0 (n_66), .Y
       (Y[1]));
  AOI31X2HVT g12537__8428(.A0 (n_46), .A1 (n_114), .A2 (n_62), .B0
       (n_63), .Y (n_69));
  OAI21X1HVT g12535__5526(.A0 (n_37), .A1 (n_61), .B0 (n_122), .Y
       (n_68));
  OAI21X1HVT g12530__6783(.A0 (n_51), .A1 (n_56), .B0 (n_43), .Y
       (n_67));
  AOI2BB1XLHVT g12534__3680(.A0N (n_30), .A1N (n_52), .B0 (n_28), .Y
       (n_66));
  AOI21X1HVT g12533__1617(.A0 (n_60), .A1 (n_38), .B0 (n_57), .Y
       (n_65));
  OAI31X2HVT g12538__2802(.A0 (n_55), .A1 (n_53), .A2 (n_54), .B0
       (n_32), .Y (n_64));
  NOR2X2HVT g12540__1705(.A (n_47), .B (n_62), .Y (n_63));
  INVX1HVT g12542(.A (n_60), .Y (n_61));
  MXI2XLHVT g12541__5122(.A (n_84), .B (n_26), .S0 (n_27), .Y (Y[0]));
  OAI21X1HVT g12548__7098(.A0 (n_44), .A1 (n_113), .B0 (n_35), .Y
       (n_57));
  AOI2BB1XLHVT g12536__6131(.A0N (n_55), .A1N (n_54), .B0 (n_53), .Y
       (n_56));
  AOI21XLHVT g12543__1881(.A0 (n_25), .A1 (n_40), .B0 (n_110), .Y
       (n_52));
  NOR2X1HVT g12547__5115(.A (n_111), .B (n_33), .Y (n_51));
  AOI21X4HVT g12546__7482(.A0 (n_16), .A1 (n_17), .B0 (n_14), .Y
       (n_62));
  OAI21X2HVT g12544__4733(.A0 (n_55), .A1 (n_95), .B0 (n_24), .Y
       (n_60));
  NAND2X2HVT g12552__9315(.A (n_46), .B (n_113), .Y (n_47));
  NAND2X1HVT g12551__9945(.A (n_44), .B (n_43), .Y (n_45));
  AOI221X1HVT g12539__2883(.A0 (n_46), .A1 (n_84), .B0 (n_40), .B1
       (n_93), .C0 (n_12), .Y (n_42));
  NOR4X2HVT g12556__2346(.A (n_18), .B (n_37), .C (n_19), .D (n_53), .Y
       (n_38));
  NAND3X1HVT g12567__1666(.A (B[3]), .B (A[3]), .C (n_31), .Y (n_35));
  OAI21X2HVT g12555__7410(.A0 (n_13), .A1 (n_31), .B0 (n_11), .Y
       (n_32));
  INVXLHVT g12558(.A (n_29), .Y (n_30));
  NOR2X1HVT g12560__6417(.A (n_21), .B (n_27), .Y (n_28));
  NOR2X1HVT g12565__5477(.A (n_9), .B (n_92), .Y (n_26));
  NOR2X2HVT g12566__2398(.A (n_20), .B (n_22), .Y (n_24));
  NOR2X1HVT g12563__6260(.A (n_55), .B (n_22), .Y (n_29));
  NOR2X1HVT g12549__4319(.A (n_25), .B (n_22), .Y (n_54));
  OAI21X2HVT g12557__8428(.A0 (n_15), .A1 (n_101), .B0 (n_21), .Y
       (n_33));
  OR2X1HVT g12568__5526(.A (n_37), .B (n_20), .Y (n_43));
  NAND2X4HVT g12561__3680(.A (n_103), .B (n_21), .Y (n_17));
  NOR2X4HVT g12559__1617(.A (n_15), .B (n_10), .Y (n_16));
  INVX1HVT g12571(.A (n_31), .Y (n_27));
  INVX3HVT g12583(.A (n_40), .Y (n_53));
  INVX1HVT g12580(.A (n_13), .Y (n_14));
  NOR2X2HVT g12573__2802(.A (A[2]), .B (n_0), .Y (n_20));
  NOR2X4HVT g12574__1705(.A (A[3]), .B (n_1), .Y (n_18));
  NOR2X4HVT g12585__5122(.A (B[3]), .B (n_4), .Y (n_19));
  NOR2X1HVT g12589__8246(.A (B[2]), .B (n_6), .Y (n_37));
  NOR2X4HVT g12576__7098(.A (B[1]), .B (n_8), .Y (n_55));
  INVX1HVT g12581(.A (n_44), .Y (n_12));
  INVX1HVT g12570(.A (n_10), .Y (n_11));
  NOR2X4HVT g12592__6131(.A (S[1]), .B (n_7), .Y (n_40));
  NOR2X2HVT g12577__1881(.A (S[0]), .B (n_5), .Y (n_31));
  NOR2X4HVT g12587__5115(.A (A[1]), .B (n_3), .Y (n_22));
  NOR2X6HVT g12579__7482(.A (A[0]), .B (n_105), .Y (n_25));
  NOR2BX1HVT g12584__4733(.AN (A[0]), .B (B[0]), .Y (n_9));
  NOR2X4HVT g12572__6161(.A (B[2]), .B (A[2]), .Y (n_10));
  NAND2X8HVT g12588__9315(.A (B[1]), .B (A[1]), .Y (n_21));
  NOR2X4HVT g12591__9945(.A (S[0]), .B (S[1]), .Y (n_46));
  NAND2X4HVT g12586__2883(.A (B[2]), .B (A[2]), .Y (n_13));
  NOR2X8HVT g12575__2346(.A (B[1]), .B (A[1]), .Y (n_15));
  NAND2X1HVT g12590__1666(.A (S[0]), .B (S[1]), .Y (n_44));
  INVX2HVT g12596(.A (A[1]), .Y (n_8));
  INVX2HVT g12601(.A (S[0]), .Y (n_7));
  INVX1HVT g12595(.A (A[2]), .Y (n_6));
  INVX1HVT g12600(.A (S[1]), .Y (n_5));
  CLKINVX4HVT g12593(.A (A[3]), .Y (n_4));
  INVX2HVT g12597(.A (B[1]), .Y (n_3));
  INVX2HVT g12598(.A (B[3]), .Y (n_1));
  INVX2HVT g12594(.A (B[2]), .Y (n_0));
  INVX1HVT fopt12604(.A (n_93), .Y (n_92));
  INVX1HVT fopt12605(.A (n_25), .Y (n_93));
  INVX3HVT fopt2(.A (n_25), .Y (n_95));
  NAND2X4HVT g12578_0__7410(.A (B[0]), .B (A[0]), .Y (n_101));
  NAND2X2HVT g12609__6417(.A (B[0]), .B (A[0]), .Y (n_84));
  NAND2X8HVT g12608_0__5477(.A (B[0]), .B (A[0]), .Y (n_103));
  CLKINVX8HVT fopt12610(.A (B[0]), .Y (n_105));
  NOR2BX1HVT g2(.AN (n_46), .B (n_84), .Y (n_110));
  INVX1HVT g12612(.A (n_46), .Y (n_111));
  INVX1HVT fopt12614(.A (n_113), .Y (n_114));
  NOR2X4HVT g12569__12615(.A (n_19), .B (n_18), .Y (n_113));
  NOR2BX1HVT g12619(.AN (n_33), .B (n_111), .Y (n_121));
  AOI2BB1X1HVT g12620(.A0N (n_19), .A1N (n_18), .B0 (n_53), .Y (n_122));
endmodule

