
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 23:31:48 +07 (Nov 19 2025 16:31:48 UTC)

// Verification Directory fv/NAND2 

module NAND2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  NAND2XLHVT g4__2398(.A (B), .B (A), .Y (Y));
endmodule

