
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 02:34:36 +07 (Nov 19 2025 19:34:36 UTC)

// Verification Directory fv/MUX21 

module MUX21(A, B, S, Y);
  input A, B, S;
  output Y;
  wire A, B, S;
  wire Y;
  MX2XLLVT g29__2398(.A (A), .B (B), .S0 (S), .Y (Y));
endmodule

