
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 14 2025 22:59:02 +07 (Dec 14 2025 15:59:02 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, clk, Y);
  input [3:0] A, B;
  input [1:0] S;
  input clk;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire clk;
  wire [3:0] Y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44;
  DFFQXLHVT \Y_reg[3] (.CK (clk), .D (n_44), .Q (Y[3]));
  NAND4XLHVT g1939__2398(.A (n_16), .B (n_35), .C (n_36), .D (n_43), .Y
       (n_44));
  DFFQXLHVT \Y_reg[2] (.CK (clk), .D (n_42), .Q (Y[2]));
  AOI31X1HVT g1944__5107(.A0 (n_22), .A1 (n_40), .A2 (n_39), .B0
       (n_41), .Y (n_43));
  OAI221X1HVT g1938__6260(.A0 (n_37), .A1 (n_25), .B0 (n_26), .B1
       (n_30), .C0 (n_38), .Y (n_42));
  NOR3XLHVT g1950__4319(.A (n_27), .B (n_40), .C (n_39), .Y (n_41));
  NAND2X1HVT g1941__8428(.A (n_37), .B (n_29), .Y (n_38));
  DFFQXLHVT \Y_reg[1] (.CK (clk), .D (n_31), .Q (Y[1]));
  OAI211X1HVT g1943__5526(.A0 (n_34), .A1 (n_32), .B0 (n_24), .C0
       (n_33), .Y (n_36));
  OR4X1HVT g1947__6783(.A (n_34), .B (n_28), .C (n_33), .D (n_32), .Y
       (n_35));
  OAI221X1HVT g1942__3680(.A0 (n_19), .A1 (n_15), .B0 (n_7), .B1
       (n_30), .C0 (n_20), .Y (n_31));
  OAI221X1HVT g1946__1617(.A0 (n_28), .A1 (n_23), .B0 (n_27), .B1
       (n_21), .C0 (n_5), .Y (n_29));
  DFFQXLHVT \Y_reg[0] (.CK (clk), .D (n_18), .Q (Y[0]));
  NAND2X1HVT g1953__2802(.A (n_26), .B (n_17), .Y (n_39));
  AOI22X1HVT g1945__1705(.A0 (n_24), .A1 (n_23), .B0 (n_22), .B1
       (n_21), .Y (n_25));
  NAND2X1HVT g1949__5122(.A (n_19), .B (n_11), .Y (n_20));
  MXI2XLHVT g1952__8246(.A (n_14), .B (n_8), .S0 (n_30), .Y (n_18));
  NOR2X1HVT g1951__7098(.A (n_6), .B (n_23), .Y (n_32));
  OAI21X1HVT g1958__6131(.A0 (B[2]), .A1 (A[2]), .B0 (n_21), .Y (n_17));
  AOI32X1HVT g1955__1881(.A0 (B[3]), .A1 (A[3]), .A2 (n_3), .B0 (n_12),
       .B1 (n_33), .Y (n_16));
  AOI21X1HVT g1954__5115(.A0 (n_13), .A1 (n_10), .B0 (n_9), .Y (n_23));
  AOI221X1HVT g1957__7482(.A0 (n_22), .A1 (n_14), .B0 (n_24), .B1
       (n_13), .C0 (n_12), .Y (n_15));
  OAI22X1HVT g1956__4733(.A0 (n_14), .A1 (n_27), .B0 (n_13), .B1
       (n_28), .Y (n_11));
  NOR2BX1HVT g1962__6161(.AN (n_10), .B (n_9), .Y (n_19));
  AND2XLHVT g1963__9315(.A (n_1), .B (n_13), .Y (n_8));
  OAI21X1HVT g1960__9945(.A0 (n_2), .A1 (n_14), .B0 (n_7), .Y (n_21));
  OR2X1HVT g1961__2883(.A (n_34), .B (n_6), .Y (n_37));
  INVX1HVT g1959(.A (n_33), .Y (n_40));
  INVX1HVT g1965(.A (n_5), .Y (n_12));
  NAND2X1HVT g1969__2346(.A (B[1]), .B (n_4), .Y (n_10));
  INVX1HVT g1966(.A (n_28), .Y (n_24));
  CLKXOR2X1HVT g1964__1666(.A (B[3]), .B (A[3]), .Y (n_33));
  NOR2X1HVT g1978__7410(.A (B[1]), .B (n_4), .Y (n_9));
  INVX1HVT g1975(.A (n_22), .Y (n_27));
  INVX1HVT g1974(.A (n_3), .Y (n_30));
  NAND2X2HVT g1972__6417(.A (B[0]), .B (n_0), .Y (n_13));
  NOR2BX1HVT g1981__5477(.AN (S[1]), .B (S[0]), .Y (n_3));
  NOR2BX1HVT g1979__2398(.AN (B[2]), .B (A[2]), .Y (n_6));
  NAND2X1HVT g1977__5107(.A (B[1]), .B (A[1]), .Y (n_7));
  NOR2BX1HVT g1980__6260(.AN (A[2]), .B (B[2]), .Y (n_34));
  NAND2X2HVT g1971__4319(.A (B[0]), .B (A[0]), .Y (n_14));
  NOR2X1HVT g1976__8428(.A (B[1]), .B (A[1]), .Y (n_2));
  NAND2BX1HVT g1967__5526(.AN (B[0]), .B (A[0]), .Y (n_1));
  NAND2X1HVT g1968__6783(.A (B[2]), .B (A[2]), .Y (n_26));
  NAND2X1HVT g1970__3680(.A (S[0]), .B (S[1]), .Y (n_5));
  NOR2X1HVT g1982__1617(.A (S[0]), .B (S[1]), .Y (n_22));
  NAND2BX1HVT g1973__2802(.AN (S[1]), .B (S[0]), .Y (n_28));
  INVX1HVT g1983(.A (A[1]), .Y (n_4));
  INVX1HVT g1984(.A (A[0]), .Y (n_0));
endmodule

