
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 01:37:40 +07 (Nov 19 2025 18:37:40 UTC)

// Verification Directory fv/OR2 

module OR2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  OR2XLLVT g2__2398(.A (B), .B (A), .Y (Y));
endmodule

