
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 18 2025 21:55:37 +07 (Dec 18 2025 14:55:37 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, Y);
  input [3:0] A, B;
  input [1:0] S;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire [3:0] Y;
  wire n_0, n_1, n_2, n_3, n_6, n_7, n_8, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_40, n_41, n_42, n_44, n_45, n_46;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_60, n_61, n_62, n_75, n_76;
  wire n_77;
  NAND3BXLHVT g8812__2398(.AN (n_60), .B (n_61), .C (n_62), .Y (Y[3]));
  OAI211X1HVT g8813__5107(.A0 (n_56), .A1 (n_38), .B0 (n_55), .C0
       (n_58), .Y (Y[2]));
  AOI21XLHVT g8815__6260(.A0 (n_46), .A1 (n_44), .B0 (n_57), .Y (n_62));
  NOR2XLHVT g8818__4319(.A (n_48), .B (n_53), .Y (n_61));
  NAND2XLHVT g8816__8428(.A (n_30), .B (n_54), .Y (n_60));
  OAI221X1HVT g8814__5526(.A0 (n_49), .A1 (n_23), .B0 (n_11), .B1
       (n_42), .C0 (n_50), .Y (Y[1]));
  MXI2XLHVT g8817__6783(.A (n_41), .B (n_28), .S0 (n_25), .Y (n_58));
  OAI21XLHVT g8819__3680(.A0 (n_56), .A1 (n_33), .B0 (n_76), .Y (n_57));
  AOI21X1HVT g8827__1617(.A0 (n_56), .A1 (n_37), .B0 (n_45), .Y (n_55));
  NAND4XLHVT g8822__2802(.A (n_18), .B (n_22), .C (n_52), .D (n_51), .Y
       (n_54));
  NOR4X1HVT g8823__1705(.A (n_14), .B (n_40), .C (n_52), .D (n_51), .Y
       (n_53));
  NAND2XLHVT g8820__5122(.A (n_49), .B (n_36), .Y (n_50));
  MXI2XLHVT g8830__8246(.A (n_27), .B (n_26), .S0 (n_52), .Y (n_48));
  OAI2BB1X1HVT g8836__6131(.A0N (n_29), .A1N (n_75), .B0 (n_21), .Y
       (n_45));
  OAI211X1HVT g8821__1881(.A0 (n_32), .A1 (n_31), .B0 (n_15), .C0
       (n_17), .Y (n_44));
  MXI2XLHVT g8826__5115(.A (n_35), .B (n_19), .S0 (n_42), .Y (Y[0]));
  NOR2XLHVT g8841__7482(.A (n_40), .B (n_75), .Y (n_41));
  NAND2XLHVT g8840__4733(.A (n_46), .B (n_75), .Y (n_38));
  NOR2XLHVT g8838__6161(.A (n_34), .B (n_75), .Y (n_37));
  OAI22XLHVT g8829__9315(.A0 (n_35), .A1 (n_34), .B0 (n_24), .B1
       (n_40), .Y (n_36));
  NAND3XLHVT g8833__9945(.A (n_46), .B (n_32), .C (n_31), .Y (n_33));
  AOI32X1HVT g8831__2883(.A0 (B[3]), .A1 (A[3]), .A2 (n_77), .B0
       (n_29), .B1 (n_31), .Y (n_30));
  NAND2XLHVT g8842__2346(.A (n_27), .B (n_26), .Y (n_28));
  INVXLHVT g8824(.A (n_51), .Y (n_25));
  AOI21X2HVT g8828__1666(.A0 (n_13), .A1 (n_24), .B0 (n_12), .Y (n_51));
  AOI221X1HVT g8832__7410(.A0 (n_35), .A1 (n_46), .B0 (n_24), .B1
       (n_22), .C0 (n_29), .Y (n_23));
  NAND2BX1HVT g8843__6417(.AN (n_32), .B (n_77), .Y (n_21));
  AND2XLHVT g8846__5477(.A (n_8), .B (n_24), .Y (n_19));
  NAND2BX1HVT g8844__2398(.AN (n_18), .B (n_22), .Y (n_27));
  INVX2HVT g8837(.A (n_31), .Y (n_52));
  NAND3BXLHVT g8834__6260(.AN (A[3]), .B (B[3]), .C (n_16), .Y (n_17));
  NAND3BXLHVT g8835__4319(.AN (B[3]), .B (A[3]), .C (n_16), .Y (n_15));
  NAND2XLHVT g8847__8428(.A (n_14), .B (n_22), .Y (n_26));
  NOR2BX1HVT g8848__5526(.AN (n_13), .B (n_12), .Y (n_49));
  OAI21X2HVT g8839__6783(.A0 (n_7), .A1 (n_35), .B0 (n_11), .Y (n_56));
  OAI22X4HVT g8849__3680(.A0 (B[3]), .A1 (n_1), .B0 (A[3]), .B1 (n_2),
       .Y (n_31));
  INVX1HVT g8850(.A (n_77), .Y (n_42));
  INVX1HVT g8861(.A (n_22), .Y (n_40));
  NOR2X1HVT g8852__1617(.A (B[1]), .B (n_3), .Y (n_12));
  NAND2X1HVT g8856__2802(.A (B[0]), .B (n_0), .Y (n_24));
  INVXLHVT g8860(.A (n_46), .Y (n_34));
  NAND2X1HVT g8864__1705(.A (B[1]), .B (n_3), .Y (n_13));
  NOR2X1HVT g8869__8246(.A (S[1]), .B (n_6), .Y (n_22));
  NAND2BXLHVT g8862__7098(.AN (B[0]), .B (A[0]), .Y (n_8));
  NOR2X2HVT g8851__6131(.A (B[1]), .B (A[1]), .Y (n_7));
  NAND2BX1HVT g8853__1881(.AN (B[2]), .B (A[2]), .Y (n_18));
  NOR2BX1HVT g8863__5115(.AN (B[2]), .B (A[2]), .Y (n_14));
  NAND2X1HVT g8854__7482(.A (B[1]), .B (A[1]), .Y (n_11));
  AND2X1HVT g8855__4733(.A (S[1]), .B (S[0]), .Y (n_29));
  NAND2X4HVT g8867__6161(.A (B[0]), .B (A[0]), .Y (n_35));
  NOR2X1HVT g8865__9315(.A (B[2]), .B (A[2]), .Y (n_16));
  NAND2X2HVT g8866__9945(.A (B[2]), .B (A[2]), .Y (n_32));
  NOR2X1HVT g8868__2883(.A (S[0]), .B (S[1]), .Y (n_46));
  INVX1HVT g8876(.A (S[0]), .Y (n_6));
  INVX1HVT g8871(.A (A[1]), .Y (n_3));
  INVX2HVT g8872(.A (B[3]), .Y (n_2));
  INVX3HVT g8873(.A (A[3]), .Y (n_1));
  INVX1HVT g8874(.A (A[0]), .Y (n_0));
  NOR2BX1HVT g2(.AN (n_32), .B (n_16), .Y (n_75));
  NAND4BXLHVT g8877(.AN (n_16), .B (n_46), .C (n_56), .D (n_52), .Y
       (n_76));
  NOR2BX1HVT g8878(.AN (S[1]), .B (S[0]), .Y (n_77));
endmodule

