
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 02:37:13 +07 (Nov 19 2025 19:37:13 UTC)

// Verification Directory fv/full_adder 

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  ADDFX1HVT g79__2398(.A (A), .B (B), .CI (Cin), .CO (Cout), .S (S));
endmodule

