
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 20 2025 02:23:49 +07 (Nov 19 2025 19:23:49 UTC)

// Verification Directory fv/NOR2 

module NOR2(A, B, Y);
  input A, B;
  output Y;
  wire A, B;
  wire Y;
  NOR2XLLVT g13__2398(.A (B), .B (A), .Y (Y));
endmodule

