
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 15 2025 22:26:40 +07 (Dec 15 2025 15:26:40 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, Y);
  input [3:0] A, B;
  input [1:0] S;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire [3:0] Y;
  wire n_0, n_1, n_2, n_3, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_15, n_16, n_17, n_18;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_38;
  OAI222X1HVT g679__2398(.A0 (n_2), .A1 (n_25), .B0 (S[1]), .B1 (n_23),
       .C0 (n_24), .C1 (n_6), .Y (Y[3]));
  OAI222XLHVT g680__5107(.A0 (n_0), .A1 (n_25), .B0 (S[1]), .B1 (n_22),
       .C0 (n_24), .C1 (n_8), .Y (Y[2]));
  XNOR2X1HVT g681__6260(.A (n_15), .B (n_20), .Y (n_23));
  INVX1HVT g682(.A (n_21), .Y (n_22));
  ADDFX1HVT g683__4319(.A (A[2]), .B (n_10), .CI (n_16), .CO (n_20), .S
       (n_21));
  OAI222XLHVT g684__8428(.A0 (n_1), .A1 (n_25), .B0 (S[1]), .B1 (n_18),
       .C0 (n_24), .C1 (n_7), .Y (Y[1]));
  INVX1HVT g685(.A (n_17), .Y (n_18));
  ADDFX1HVT g686__5526(.A (A[1]), .B (n_13), .CI (n_9), .CO (n_16), .S
       (n_17));
  XNOR2X1HVT g689__6783(.A (A[3]), .B (n_12), .Y (n_15));
  OAI21X1HVT g688__1617(.A0 (B[0]), .A1 (n_11), .B0 (n_3), .Y (n_13));
  MXI2XLHVT g691__2802(.A (S[0]), .B (n_11), .S0 (B[3]), .Y (n_12));
  MX2XLHVT g692__1705(.A (S[0]), .B (n_11), .S0 (B[2]), .Y (n_10));
  MXI2XLHVT g693__5122(.A (n_11), .B (S[0]), .S0 (B[1]), .Y (n_9));
  XNOR2X1HVT g695__8246(.A (B[2]), .B (A[2]), .Y (n_8));
  XNOR2X1HVT g694__7098(.A (B[1]), .B (A[1]), .Y (n_7));
  XNOR2X1HVT g696__6131(.A (B[3]), .B (A[3]), .Y (n_6));
  NAND2X1HVT g700__5115(.A (S[1]), .B (n_11), .Y (n_25));
  NAND2X1HVT g698__7482(.A (B[3]), .B (A[3]), .Y (n_2));
  NAND2X1HVT g699__4733(.A (S[0]), .B (S[1]), .Y (n_24));
  NAND2X1HVT g701__6161(.A (B[1]), .B (A[1]), .Y (n_1));
  NAND2X1HVT g702__9315(.A (B[2]), .B (A[2]), .Y (n_0));
  NAND2X1HVT g703__9945(.A (B[0]), .B (A[0]), .Y (n_3));
  INVX1HVT g704(.A (S[0]), .Y (n_11));
  MXI2XLHVT g2(.A (n_3), .B (n_38), .S0 (n_25), .Y (Y[0]));
  XNOR2X1HVT g3(.A (B[0]), .B (A[0]), .Y (n_38));
endmodule

