
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 15 2025 15:59:21 +07 (Dec 15 2025 08:59:21 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, clk, Y);
  input [3:0] A, B;
  input [1:0] S;
  input clk;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire clk;
  wire [3:0] Y;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_8, n_9, n_10, n_12, n_13, n_14, n_19, n_20;
  wire n_21, n_22, n_23, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_61, n_62, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_95, n_96;
  wire n_101, n_102, n_103, n_104, n_107, n_109, n_112, n_113;
  wire n_114;
  DFFQXLHVT \Y_reg[2] (.CK (clk), .D (n_79), .Q (Y[2]));
  NAND2X1HVT g10728__2398(.A (n_72), .B (n_78), .Y (n_80));
  DFFQXLHVT \Y_reg[1] (.CK (clk), .D (n_77), .Q (Y[1]));
  OAI22X1HVT g10729__5107(.A0 (n_62), .A1 (n_76), .B0 (n_112), .B1
       (n_114), .Y (n_79));
  NOR2X1HVT g10730__6260(.A (n_74), .B (n_75), .Y (n_78));
  NAND2XLHVT g10731__4319(.A (n_69), .B (n_70), .Y (n_77));
  NOR2X1HVT g10734__8428(.A (n_52), .B (n_65), .Y (n_76));
  OAI21X1HVT g10732__5526(.A0 (n_73), .A1 (n_54), .B0 (n_59), .Y
       (n_75));
  AOI2BB1X1HVT g10737__6783(.A0N (n_41), .A1N (n_73), .B0 (n_47), .Y
       (n_74));
  AOI21X1HVT g10740__3680(.A0 (n_50), .A1 (n_66), .B0 (n_67), .Y
       (n_72));
  DFFQXLHVT \Y_reg[0] (.CK (clk), .D (n_64), .Q (Y[0]));
  AOI2BB1XLHVT g10736__2802(.A0N (n_68), .A1N (n_53), .B0 (n_29), .Y
       (n_70));
  OAI31X1HVT g10733__1705(.A0 (n_61), .A1 (n_30), .A2 (n_40), .B0
       (n_68), .Y (n_69));
  NOR2X1HVT g10742__5122(.A (n_48), .B (n_66), .Y (n_67));
  OAI31X1HVT g10741__8246(.A0 (n_57), .A1 (n_55), .A2 (n_56), .B0
       (n_37), .Y (n_65));
  MXI2XLHVT g10743__7098(.A (n_27), .B (n_31), .S0 (n_35), .Y (n_64));
  NOR2X2HVT g10745__1881(.A (n_45), .B (n_38), .Y (n_73));
  NOR2X1HVT g10754__5115(.A (n_61), .B (n_112), .Y (n_62));
  AOI21X1HVT g10751__7482(.A0 (n_61), .A1 (n_49), .B0 (n_113), .Y
       (n_59));
  AOI2BB1XLHVT g10739__4733(.A0N (n_57), .A1N (n_56), .B0 (n_55), .Y
       (n_58));
  NAND2X2HVT g10759__6161(.A (n_42), .B (n_44), .Y (n_54));
  AOI21XLHVT g10744__9315(.A0 (n_39), .A1 (n_46), .B0 (n_32), .Y
       (n_53));
  NOR2X1HVT g10747__9945(.A (n_51), .B (n_33), .Y (n_52));
  OAI2BB1X1HVT g10748__2883(.A0N (n_95), .A1N (n_20), .B0 (n_104), .Y
       (n_66));
  NOR2X1HVT g10755__2346(.A (n_51), .B (n_49), .Y (n_50));
  NAND2X1HVT g10756__1666(.A (n_13), .B (n_49), .Y (n_48));
  NAND2X1HVT g10760__7410(.A (n_46), .B (n_49), .Y (n_47));
  NAND2X4HVT g10770__6417(.A (n_23), .B (n_19), .Y (n_45));
  NOR2BX2HVT g10769__5477(.AN (n_28), .B (n_55), .Y (n_44));
  NOR2X1HVT g10772__5107(.A (n_41), .B (n_22), .Y (n_42));
  NOR2X1HVT g10750__6260(.A (n_39), .B (n_55), .Y (n_40));
  NOR2X2HVT g10749__4319(.A (n_57), .B (n_107), .Y (n_38));
  OAI21X2HVT g10758__8428(.A0 (n_103), .A1 (n_35), .B0 (n_12), .Y
       (n_37));
  INVXLHVT g10757(.A (n_33), .Y (n_34));
  NOR2X1HVT g10766__6783(.A (n_31), .B (n_51), .Y (n_32));
  NOR2BX1HVT g10765__3680(.AN (n_31), .B (n_51), .Y (n_30));
  AND2XLHVT g10763__1617(.A (n_35), .B (n_26), .Y (n_29));
  NAND2X2HVT g10767__2802(.A (n_28), .B (n_21), .Y (n_49));
  NOR2X1HVT g10771__1705(.A (n_10), .B (n_39), .Y (n_27));
  OR2XLHVT g10774__5122(.A (n_57), .B (n_25), .Y (n_68));
  AOI2BB1X1HVT g10761__8246(.A0N (n_31), .A1N (n_96), .B0 (n_26), .Y
       (n_33));
  NOR2X1HVT g10752__7098(.A (n_39), .B (n_25), .Y (n_56));
  INVX1HVT g10776(.A (n_21), .Y (n_22));
  NAND2X1HVT g10762__6131(.A (n_14), .B (n_31), .Y (n_20));
  INVX3HVT g10789(.A (n_25), .Y (n_19));
  INVX3HVT g10791(.A (n_46), .Y (n_55));
  NAND2X4HVT g10780__5115(.A (B[3]), .B (n_109), .Y (n_28));
  INVX1HVT g10777(.A (n_14), .Y (n_26));
  NOR2X4HVT g10800__7482(.A (S[1]), .B (n_2), .Y (n_46));
  NOR2X2HVT g10799__4733(.A (S[0]), .B (n_1), .Y (n_35));
  NOR2X2HVT g10798__6161(.A (B[1]), .B (n_5), .Y (n_57));
  INVX2HVT g10778(.A (n_13), .Y (n_51));
  INVX1HVT g10775(.A (n_101), .Y (n_12));
  NOR2X1HVT g10792__9315(.A (B[0]), .B (n_3), .Y (n_10));
  NAND2X2HVT g10782__9945(.A (A[3]), .B (n_6), .Y (n_21));
  NAND2X2HVT g10795__2883(.A (B[2]), .B (n_9), .Y (n_23));
  NOR2X4HVT g10797__2346(.A (A[1]), .B (n_0), .Y (n_25));
  NOR2X1HVT g10783__1666(.A (B[2]), .B (n_9), .Y (n_41));
  NOR2X4HVT g10785__7410(.A (A[0]), .B (n_4), .Y (n_39));
  CLKAND2X2HVT g10796__5107(.A (S[0]), .B (S[1]), .Y (n_61));
  NAND2X1HVT g10793__6260(.A (B[3]), .B (A[3]), .Y (n_8));
  NAND2X4HVT g10784__4319(.A (B[1]), .B (A[1]), .Y (n_14));
  NOR2X2HVT g10787__8428(.A (S[0]), .B (S[1]), .Y (n_13));
  NAND2X6HVT g10786__5526(.A (B[0]), .B (A[0]), .Y (n_31));
  INVX2HVT g10802(.A (B[3]), .Y (n_6));
  INVX2HVT g10808(.A (A[1]), .Y (n_5));
  INVX2HVT g10807(.A (A[2]), .Y (n_9));
  CLKINVX4HVT g10806(.A (B[0]), .Y (n_4));
  INVX1HVT g10805(.A (A[0]), .Y (n_3));
  INVX3HVT g10803(.A (S[0]), .Y (n_2));
  INVX2HVT g10809(.A (S[1]), .Y (n_1));
  CLKINVX6HVT g10804(.A (B[1]), .Y (n_0));
  DFFXLHVT \Y_reg[3] (.CK (clk), .D (n_80), .Q (Y[3]), .QN
       (UNCONNECTED));
  AOI2BB1XLHVT g2(.A0N (B[1]), .A1N (A[1]), .B0 (n_102), .Y (n_95));
  NOR2X1HVT g10781__10816(.A (B[1]), .B (A[1]), .Y (n_96));
  NOR2X1HVT g10779__10820(.A (B[2]), .B (A[2]), .Y (n_101));
  NOR2X2HVT g10779__6417_0(.A (B[2]), .B (A[2]), .Y (n_102));
  NAND2X4HVT g10794__10821(.A (B[2]), .B (A[2]), .Y (n_103));
  NAND2X2HVT g10794__5477_0(.A (B[2]), .B (A[2]), .Y (n_104));
  INVX2HVT fopt1(.A (n_39), .Y (n_107));
  CLKINVX8HVT fopt10822(.A (A[3]), .Y (n_109));
  NOR2BX1HVT g10824(.AN (n_23), .B (n_41), .Y (n_112));
  NOR2BX1HVT g10825(.AN (n_35), .B (n_8), .Y (n_113));
  AOI2BB1X1HVT g10826(.A0N (n_51), .A1N (n_34), .B0 (n_58), .Y (n_114));
endmodule

