
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 18 2025 20:47:13 +07 (Nov 18 2025 13:47:13 UTC)

// Verification Directory fv/dff 

module dff(clk, d, q);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFHQX1HVT q_reg(.CK (clk), .D (d), .Q (q));
endmodule

