
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 18 2025 20:00:24 +07 (Nov 18 2025 13:00:24 UTC)

// Verification Directory fv/dff 

module dff(clk, d, q);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFQXLHVT q_reg(.CK (clk), .D (d), .Q (q));
endmodule

