
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 14 2025 22:55:15 +07 (Dec 14 2025 15:55:15 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, clk, Y);
  input [3:0] A, B;
  input [1:0] S;
  input clk;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire clk;
  wire [3:0] Y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26;
  DFFQXLHVT \Y_reg[3] (.CK (clk), .D (n_26), .Q (Y[3]));
  DFFQXLHVT \Y_reg[2] (.CK (clk), .D (n_25), .Q (Y[2]));
  OAI222X1HVT g656__2398(.A0 (n_24), .A1 (n_5), .B0 (S[1]), .B1 (n_22),
       .C0 (n_4), .C1 (n_23), .Y (n_26));
  OAI222X1HVT g658__5107(.A0 (n_24), .A1 (n_12), .B0 (S[1]), .B1
       (n_21), .C0 (n_11), .C1 (n_23), .Y (n_25));
  XNOR2X1HVT g659__6260(.A (n_14), .B (n_19), .Y (n_22));
  INVX1HVT g660(.A (n_20), .Y (n_21));
  ADDFX1HVT g661__4319(.A (A[2]), .B (n_3), .CI (n_15), .CO (n_19), .S
       (n_20));
  DFFQXLHVT \Y_reg[1] (.CK (clk), .D (n_18), .Q (Y[1]));
  OAI222X1HVT g663__8428(.A0 (n_24), .A1 (n_10), .B0 (S[1]), .B1
       (n_17), .C0 (n_9), .C1 (n_23), .Y (n_18));
  INVX1HVT g664(.A (n_16), .Y (n_17));
  ADDFX1HVT g665__5526(.A (A[1]), .B (n_13), .CI (n_6), .CO (n_15), .S
       (n_16));
  XNOR2X1HVT g668__6783(.A (A[3]), .B (n_8), .Y (n_14));
  SDFFQX1HVT \Y_reg[0] (.CK (clk), .D (n_2), .SI (n_0), .SE (n_23), .Q
       (Y[0]));
  OAI21X1HVT g667__3680(.A0 (B[0]), .A1 (n_7), .B0 (n_1), .Y (n_13));
  OAI21X1HVT g670__1617(.A0 (B[2]), .A1 (A[2]), .B0 (n_11), .Y (n_12));
  OAI21X1HVT g671__2802(.A0 (B[1]), .A1 (A[1]), .B0 (n_9), .Y (n_10));
  MXI2XLHVT g675__1705(.A (S[0]), .B (n_7), .S0 (B[3]), .Y (n_8));
  MXI2XLHVT g674__5122(.A (n_7), .B (S[0]), .S0 (B[1]), .Y (n_6));
  OAI21X1HVT g672__8246(.A0 (B[3]), .A1 (A[3]), .B0 (n_4), .Y (n_5));
  MXI2XLHVT g676__7098(.A (n_7), .B (S[0]), .S0 (B[2]), .Y (n_3));
  INVXLHVT g669(.A (n_1), .Y (n_2));
  XOR2XLHVT g673__6131(.A (B[0]), .B (A[0]), .Y (n_0));
  NAND2X1HVT g679__1881(.A (S[1]), .B (n_7), .Y (n_23));
  NAND2X1HVT g680__5115(.A (B[3]), .B (A[3]), .Y (n_4));
  NAND2X1HVT g682__7482(.A (B[2]), .B (A[2]), .Y (n_11));
  NAND2X1HVT g677__4733(.A (B[1]), .B (A[1]), .Y (n_9));
  NAND2X1HVT g681__6161(.A (B[0]), .B (A[0]), .Y (n_1));
  NAND2X1HVT g678__9315(.A (S[0]), .B (S[1]), .Y (n_24));
  INVX1HVT g683(.A (S[0]), .Y (n_7));
endmodule

