
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 19 2025 22:55:32 +07 (Nov 19 2025 15:55:32 UTC)

// Verification Directory fv/NOT 

module NOT(A, Y);
  input A;
  output Y;
  wire A;
  wire Y;
  INVXLHVT g2(.A (A), .Y (Y));
endmodule

