
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Dec 14 2025 23:13:03 +07 (Dec 14 2025 16:13:03 UTC)

// Verification Directory fv/alu 

module alu(A, B, S, clk, Y);
  input [3:0] A, B;
  input [1:0] S;
  input clk;
  output [3:0] Y;
  wire [3:0] A, B;
  wire [1:0] S;
  wire clk;
  wire [3:0] Y;
  wire n_0, n_2, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_14, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_33, n_34, n_37, n_38, n_39, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_77, n_78;
  wire n_79, n_80, n_81;
  DFFQXLHVT \Y_reg[2] (.CK (clk), .D (n_65), .Q (Y[2]));
  DFFQXLHVT \Y_reg[3] (.CK (clk), .D (n_64), .Q (Y[3]));
  OAI22X1HVT g12445__2398(.A0 (n_42), .A1 (n_63), .B0 (n_78), .B1
       (n_62), .Y (n_65));
  NAND4XLHVT g12444__5107(.A (n_43), .B (n_77), .C (n_59), .D (n_56),
       .Y (n_64));
  DFFQXLHVT \Y_reg[1] (.CK (clk), .D (n_60), .Q (Y[1]));
  AOI21X1HVT g12447__6260(.A0 (n_61), .A1 (n_27), .B0 (n_54), .Y
       (n_63));
  AOI22X1HVT g12448__4319(.A0 (n_61), .A1 (n_28), .B0 (n_58), .B1
       (n_46), .Y (n_62));
  OAI221X1HVT g12446__8428(.A0 (n_47), .A1 (n_39), .B0 (n_25), .B1
       (n_53), .C0 (n_48), .Y (n_60));
  OAI211X1HVT g12449__5526(.A0 (n_31), .A1 (n_49), .B0 (n_58), .C0
       (n_55), .Y (n_59));
  AOI31X1HVT g12453__3680(.A0 (n_61), .A1 (n_55), .A2 (n_51), .B0
       (n_52), .Y (n_56));
  OAI32X1HVT g12454__1617(.A0 (n_45), .A1 (n_81), .A2 (n_44), .B0
       (n_18), .B1 (n_23), .Y (n_54));
  SDFFQX1HVT \Y_reg[0] (.CK (clk), .D (n_8), .SI (n_30), .SE (n_53), .Q
       (Y[0]));
  NOR2X1HVT g12457__2802(.A (n_34), .B (n_51), .Y (n_52));
  NAND2X1HVT g12452__1705(.A (n_47), .B (n_38), .Y (n_48));
  OR2XLHVT g12456__5122(.A (n_45), .B (n_44), .Y (n_46));
  NOR2X1HVT g12460__8246(.A (n_24), .B (n_29), .Y (n_49));
  AOI32X1HVT g12463__7098(.A0 (B[3]), .A1 (A[3]), .A2 (n_22), .B0
       (n_41), .B1 (n_55), .Y (n_43));
  NOR2X1HVT g12466__6131(.A (n_41), .B (n_78), .Y (n_42));
  AOI221X1HVT g12455__1881(.A0 (n_61), .A1 (n_37), .B0 (n_58), .B1
       (n_11), .C0 (n_41), .Y (n_39));
  OAI22X1HVT g12459__5115(.A0 (n_37), .A1 (n_33), .B0 (n_11), .B1
       (n_81), .Y (n_38));
  OR2XLHVT g12467__7482(.A (n_33), .B (n_55), .Y (n_34));
  AOI21X1HVT g12462__6161(.A0 (n_20), .A1 (n_21), .B0 (n_6), .Y (n_51));
  OAI2BB1X1HVT g12476__9315(.A0N (A[0]), .A1N (n_7), .B0 (n_11), .Y
       (n_30));
  NOR2X1HVT g12478__9945(.A (n_45), .B (n_26), .Y (n_47));
  NOR2X1HVT g12461__2346(.A (n_45), .B (n_11), .Y (n_29));
  INVX1HVT g12468(.A (n_27), .Y (n_28));
  NOR2X1HVT g12464__1666(.A (n_10), .B (n_26), .Y (n_44));
  OAI21X1HVT g12470__7410(.A0 (n_19), .A1 (n_37), .B0 (n_25), .Y
       (n_27));
  NAND2X1HVT g12475__6417(.A (n_80), .B (n_9), .Y (n_24));
  NAND2X1HVT g12474__5477(.A (n_14), .B (n_12), .Y (n_55));
  NOR2X1HVT g12473__2398(.A (n_5), .B (n_22), .Y (n_23));
  NAND2X1HVT g12472__5107(.A (n_25), .B (n_37), .Y (n_21));
  NOR2X1HVT g12471__6260(.A (n_19), .B (n_18), .Y (n_20));
  INVX1HVT g12494(.A (n_9), .Y (n_26));
  INVX2HVT g12465(.A (n_10), .Y (n_11));
  INVX1HVT g12496(.A (n_81), .Y (n_58));
  INVXLHVT g12482(.A (n_37), .Y (n_8));
  INVX1HVT g12483(.A (n_61), .Y (n_33));
  NAND2X1HVT g12484__4319(.A (A[3]), .B (n_0), .Y (n_14));
  NAND2X1HVT g12485__8428(.A (B[3]), .B (n_2), .Y (n_12));
  NOR2X2HVT g12489__5526(.A (A[0]), .B (n_7), .Y (n_10));
  INVX1HVT g12493(.A (n_5), .Y (n_6));
  NAND2X2HVT g12500__6783(.A (B[1]), .B (n_4), .Y (n_9));
  INVX1HVT g12495(.A (n_22), .Y (n_53));
  NOR2X2HVT g12502__1617(.A (B[1]), .B (n_4), .Y (n_45));
  NOR2X1HVT g12486__1705(.A (B[1]), .B (A[1]), .Y (n_19));
  NAND2X1HVT g12499__5122(.A (B[2]), .B (A[2]), .Y (n_5));
  NAND2X1HVT g12487__8246(.A (B[1]), .B (A[1]), .Y (n_25));
  NAND2X2HVT g12490__7098(.A (B[0]), .B (A[0]), .Y (n_37));
  NOR2X1HVT g12498__6131(.A (B[2]), .B (A[2]), .Y (n_18));
  NOR2BX1HVT g12488__1881(.AN (A[2]), .B (B[2]), .Y (n_31));
  NOR2BX1HVT g12503__5115(.AN (S[1]), .B (S[0]), .Y (n_22));
  AND2X1HVT g12501__7482(.A (S[1]), .B (S[0]), .Y (n_41));
  NOR2X1HVT g12491__4733(.A (S[0]), .B (S[1]), .Y (n_61));
  INVX1HVT g12505(.A (A[3]), .Y (n_2));
  INVX2HVT g12507(.A (B[0]), .Y (n_7));
  INVX1HVT g12506(.A (B[3]), .Y (n_0));
  INVX2HVT g12509(.A (A[1]), .Y (n_4));
  NAND2BX1HVT g2(.AN (n_49), .B (n_79), .Y (n_77));
  NOR2BX1HVT g12515(.AN (n_80), .B (n_31), .Y (n_78));
  NOR4BBX1HVT g12516(.AN (n_14), .BN (n_12), .C (n_31), .D (n_81), .Y
       (n_79));
  NAND2BX1HVT g12517(.AN (A[2]), .B (B[2]), .Y (n_80));
  NAND2BX1HVT g12518(.AN (S[1]), .B (S[0]), .Y (n_81));
endmodule

